### ISSUE TITLE
Home assistant reporting wrong energy consumption

### ISSUE THREAD

**Issue by topiw** [vilppuvuorinen/pymelcloud#17] opened 2022-02-14 07:26 UTC
Hello

The Melcloud estimated energy consumption was changed some time ago. Now home assistant is reporting different daily energy consumption than Melcloud. At least when using MUZ-LN25VG(HZ)2, MSZ-LN25VG2(W/V/R/B) ATA model.

Here are the daily energy usages in kWh reported by HA and Melcloud in last few days:
Date  HA	  Melcloud
13/2	  2.0	  14.4
12/2	  2.4	  15.5
11/2	  2.6	  16.7
10/2	  2.4	  14.4

**Comment by vilppuvuorinen** [comment] 2022-02-14 10:03
I compared the numbers for my unit and they were pretty close between HA and MELCloud. Not identical for some reason.

The energy consumption is read from `Device.CurrentEnergyConsumed`of the `ListDevices` response without other conversions besides the Wh->kWh one. You should check `Device.CurrentEnergyMode`, `Device.EnergyCorrectionActive` and `Device.EnergyCorrectionModel` fields from the same response and paste them here.

**Comment by topiw** [comment] 2022-02-14 13:07
From where I can get the response?

**Comment by vilppuvuorinen** [comment] 2022-02-14 13:19
Like this:
1. Open MELCloud in browser
2. Press F12 to open developer tools
3. Go to the Network tab
4. Refresh the page
5. Open `ListDevices` request in the Network tab.
6. Open response body (Preview sub tab in Chrome)

You can search the response with Ctrl+F.

**Comment by topiw** [comment] 2022-02-14 13:23
"CurrentEnergyMode":1,
"EnergyCorrectionActive":true,
"EnergyCorrectionModel":919,

**Comment by HenkeGoransson** [comment] 2022-03-03 07:56
The really weird part is I pulled the power yesterday. And now it is reporting closer to the correct value. 
In the first 6h of this day:
4,8kWh(HA) vs 5,6kWh(melcloud)


I have:
CurrentEnergyMode:1,
EnergyCorrectionActive: false
EnergyCorrectionModel: 561

**Comment by esponjaman** [comment] 2022-03-04 19:27
> 

There is a update of firmware to correct wrong values of the measured energy consumption. Only mono splits units are affected.
[https://www.melcloud.com/en/Support](url)
```
MELCLOUD SERVICE UPDATE (1/2/22)
We have identified an issue with energy data being incorrectly reported in MELCloud for some single-split Room Air Conditioners, we have now deployed the correction logic to our servers.

If you have single-split Room Air Conditioner, please could you power off the system via the MELCloud App for a period of 10 minutes, this power off action will trigger the energy correction logic update for your system.

Please note: Multi-splits, Ecodan, Mr Slim and City Multi systems are not affected by this issue.
```
The value reported in HA is the one available in the json of the site, with the tag "CurrentEnergyConsumed". But for my units it calculates from that value to something completely different. But my bet is that the calculated value is closer to reality, since I don't have any meter in them I cannot say for sure.

**Comment by vilppuvuorinen** [comment] 2022-03-07 15:20
@esponjaman That's a lot of info. Did I read that correctly tho? Are the issues being fixed by an update that is already being rolled out?

I've done some experiments with the report endpoint and it is totally possible to pull data out of it. I'm just not too eager to ship something that uses it because:

* The update interval would be super slow.
* The counter in the device state fits a lot better to the energy consumption tracking primitives in home-assistant.
* The report endpoint appeared (at least back when I was looking into it the last time) a bit too slow to my taste. It's not something that would be an issue from performance view point, but I don't want to cause any extra load towards the servers that would prompt actions to prevent it.

**Comment by esponjaman** [comment] 2022-03-07 16:03
> That's a lot of info. Did I read that correctly tho? Are the issues being fixed by an update that is already being rolled out?

My units, since all of them are single-split ones, have received the update, all of them report in the ListDevices that attribute:
EnergyCorrectionActive	TRUE
I think that's the reason for totally different values between the report option of the melcloud app, and the one in the ListDevices. Instead of correcting it on the source they do some kind of math with that value and present a different, more close to reality, i think, in the report section.

>The update interval would be super slow.

Have to test the update interval of the report, maybe its only every hour, even so, you can include this in you 5 minutes routines, as we stand now, I don't think that the current value is updated that much often.

> The counter in the device state fits a lot better to the energy consumption tracking primitives in home-assistant.

I'm with you in this one, the current value is an always increasing value so the logic is the same as in home-assistant.

>The report endpoint appeared (at least back when I was looking into it the last time) a bit too slow to my taste. It's not something that would be an issue from performance view point, but I don't want to cause any extra load towards the servers that would prompt actions to prevent it.

Must be you, in my end is really fast. About 0.3s of the time interval: 
"FromDate":"2021-03-03T00:00:00","ToDate":"2022-03-06T00:00:00"
> curl 'https://app.melcloud.com/Mitsubishi.Wifi.Client/EnergyCost/Report'   
-H 'authority: app.melcloud.com'   
-H 'sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="98", "Microsoft Edge";v="98"'   
-H 'x-mitscontextkey: XXXXXX_KEY_CHANGED_XXXXXXXX'   
-H 'sec-ch-ua-mobile: ?0'   
-H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36 Edg/98.0.1108.62'   
-H 'content-type: application/json; charset=UTF-8'   
-H 'accept: application/json, text/javascript, */*; q=0.01'   -H 'x-requested-with: XMLHttpRequest'   
-H 'sec-ch-ua-platform: "Windows"'   
-H 'origin: https://app.melcloud.com'   
-H 'sec-fetch-site: same-origin'   
-H 'sec-fetch-mode: cors'   
-H 'sec-fetch-dest: empty'   
-H 'referer: https://app.melcloud.com/'  
 -H 'accept-language: pt-PT,pt;q=0.9,en-US;q=0.8,en;q=0.7'   
--data-raw '{"XXXX_DEVICE_ID_CHANGED_XXXXX":33567928,"FromDate":"2021-03-03T00:00:00","ToDate":"2022-03-06T00:00:00","UseCurrency":false}'   
--compressed  
-w "%{time_namelookup}s\n 
%{time_connect}s\n 
%{time_appconnect}s\n 
%{time_pretransfer}s\n 
%{time_redirect}s\n 
%{time_starttransfer}s\n 
%{time_total}s\n"

 0.110876s
 0.213612s
 0.214008s
 0.000000s
 0.214064s
 0.306853s

**Comment by esponjaman** [comment] 2022-03-09 12:20
@vilppuvuorinen confirmed the report is available for the current day, the moment the CurrentEnergyConsumed is updated/incremented. So there is not extra delay comparing to the current method.

**Comment by HenkeGoransson** [comment] 2022-05-18 07:13
My unit did not receive any FW update and are still reporting wrong value.
Any progress with a solution?

**Comment by Nikuc** [comment] 2022-06-30 20:05
My unit did not receive any FW update and are still reporting wrong value.
Any progress with a solution?

**Comment by Nikuc** [comment] 2022-07-23 04:22
> I compared the numbers for my unit and they were pretty close between HA and MELCloud. Not identical for some reason.
> 
> The energy consumption is read from `Device.CurrentEnergyConsumed`of the `ListDevices` response without other conversions besides the Wh->kWh one. You should check `Device.CurrentEnergyMode`, `Device.EnergyCorrectionActive` and `Device.EnergyCorrectionModel` fields from the same response and paste them here.

"CurrentEnergyMode":3
"EnergyCorrectionActive":true
EnergyCorrectionModel":562

**Comment by Nikuc** [comment] 2022-07-23 04:23
"CurrentEnergyMode":3
"EnergyCorrectionActive":true
EnergyCorrectionModel":562

**Comment by Exclution** [comment] 2022-08-08 20:17
Hi all,

My device is showing 
CurrentEnergyMode:3
EnergyCorrectionActive: false
EnergyCorrectionModel:556
CurrentEnergyConsumed:18100

Obviously in melcloud m energy consumption is wrong at all...

What is wrong here? This is a multispliz, so Firmware Update has not loaded...

**Comment by IDDQD69** [comment] 2022-10-15 08:41
Hi! 

I have a two MSZ-LN25VG/W units in a single MXZ-2E53VAHZ (ATA), and everything is working fine, but I am not getting any power consumption data? Is there some other device required to see kw/h?

**Comment by vilppuvuorinen** [comment] 2022-10-15 09:42
Try updating home assistant and use the daily energy consumed sensor. The value resets daily, but it should be possible to get things working with some utility meter configuration.

**Comment by IDDQD69** [comment] 2022-10-15 11:24
Problem is not with home-assistant, I do not get that data at all. Should basic air to air pumps even gather energy consumption by themselves?

**Comment by vilppuvuorinen** [comment] 2022-10-15 12:01
Air to air pumps usually have an energy counter, but it sometimes does not work as expected due to some correction system.

2.5.8 version of this library introduces a new `daily_energy_consumed` property that reports the daily consumption. It resets at midnight on the tz MELCloud uses.

**Comment by HenkeGoransson** [comment] 2022-10-15 12:05
@vilppuvuorinen
Thanks alot for this fix! It works perfectly!
I think this issue can be closed now

**Closed** 2022-10-15 13:43 UTC

**Comment by IDDQD69** [comment] 2022-10-15 13:47
Tried version from master and:

`print(device.name)
 print(device.daily_energy_consumed)
 print(device.total_energy_consumed)
`
returns 

`makkari ilp
0.0
None
`

I'll keep contacting MELcloud support, for some reason kw/h are not shown. I've tried to re-enter my devices etc.

thanks.

**Comment by vilppuvuorinen** [comment] 2022-10-15 14:06
IIRC these setups with multiple indoor units report energy consumption in a weird way.

1. How many devices do you see in MELCloud for this setup?
2. What do the energy reports look like in MELCloud?

**Comment by IDDQD69** [comment] 2022-10-15 14:24
2 indoor units, both have a wifi-dongle. Energy consumption reports are hidden completely. Indoor units re connected as multi-split system.

**Comment by Nikuc** [comment] 2022-10-16 15:26
hi, may somebody show me on simple way what i do for wrong value for energy consumption i have ln50 i use melcloud from andoid and windows,  [2.5.8] - 2022-09-18 this version of what, where i find and update? Thanks

**Comment by vilppuvuorinen** [comment] 2022-10-17 10:27
@Nikuc Have you tried using the `daily_energy_consumed` property? (https://github.com/vilppuvuorinen/pymelcloud/blob/v2.5.x/pymelcloud/device.py#L189)
